AWSTemplateFormatVersion: 2010-09-09
Description: LMS Infrastructure 
Resources:
  # VPC
  lmsVPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: lms-vpc
  # Web Subnet          
  lmswebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "eu-west-2a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: lms-web-subnet
  # App Subnet          
  lmsappSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "eu-west-2a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: lms-app-subnet
  # DB Subnet          
  lmsdbSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "eu-west-2a"
      MapPublicIpOnLaunch: "false"
      Tags:
      - Key: Name
        Value: lms-db-subnet
  # Internet Gateway
  lmsInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: lms-igw

  # Attach Internet Gateway      
  lmsAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: lmsVPC
      InternetGatewayId:
        Ref: lmsInternetGateway
  
  # Public Route Table
  lmspubRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: lmsVPC
      Tags:
      - Key: Name
        Value: lms-pub-rt

  # Internet Route 
  myRoute:
    Type: AWS::EC2::Route
    DependsOn: lmsAttachGateway
    Properties:
       RouteTableId:
         Ref: lmspubRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: lmsInternetGateway
    
  # RT - Subnet Association 
  lmswebSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: lmswebSubnet
      RouteTableId:
        Ref: lmspubRouteTable

  # RT - Subnet Association 
  lmsappSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: lmsappSubnet
      RouteTableId:
        Ref: lmspubRouteTable

  # Private Route Table
  lmspvtRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: lmsVPC
      Tags:
      - Key: Name
        Value: lms-pvt-rt

  # RT - Subnet Association 
  lmsdbSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: lmsdbSubnet
      RouteTableId:
        Ref: lmspvtRouteTable
  
  # RT - Subnet Association 
  lmswebNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: lmsVPC
      Tags:
        - Key: Name
          Value: lms-web-nacl
  
# Web NACL Rules
  lmswebnaclInboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: lmswebNetworkAcl
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
       PortRange:
         From: 0
         To: 65535
  lmswebnaclOutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: lmswebNetworkAcl
       RuleNumber: 100
       Protocol: -1
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0

# Web NACL Association       
  lmswebSubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId:
        Ref: lmswebSubnet
      NetworkAclId:
        Ref: lmswebNetworkAcl

# App NACL 
  lmsappNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: lmsVPC
      Tags:
        - Key: Name
          Value: lms-app-nacl
  
# App NACL Rules
lmsappnaclInboundRule:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
     NetworkAclId:
       Ref: lmsappNetworkAcl
     RuleNumber: 100
     Protocol: 6
     RuleAction: allow
     CidrBlock: 0.0.0.0/0
     PortRange:
       From: 0
       To: 65535
lmsappnaclOutboundRule:
  Type: AWS::EC2::NetworkAclEntry
  Properties:
     NetworkAclId:
       Ref: lmsappNetworkAcl
     RuleNumber: 100
     Protocol: -1
     Egress: true
     RuleAction: allow
     CidrBlock: 0.0.0.0/0

