AWSTemplateFormatVersion: 2010-09-09
Description: LMS Infrastructure 
Resources:
  # VPC
  lmsVPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: lms-vpc
  # Web Subnet          
  lmswebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "eu-west-2a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: lms-web-subnet
  # App Subnet          
  lmsappSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "eu-west-2a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: lms-app-subnet